sudo: required
dist: trusty
branches:
  only:
  - gh-pages
  - /.*/
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - postfix
language: php
php:
  - 7.0
env:
  global:
    - MAGENTO_CE_VERSION=2.1.7
    - COMPOSER_BIN_DIR=~/bin
cache:
  apt: true
  directories: $HOME/.composer/cache
before_install:
  # disable xdebug for perf
  - phpenv config-rm xdebug.ini
  # Get latest version of composer
  - composer selfupdate
  # Clone main magento github repository
  - git clone https://github.com/magento/magento2 --branch $MAGENTO_CE_VERSION --depth 1
  - cd magento2
  - composer require vendic/module-regenerateproducturls
before_script:
  - chmod +x ./dev/travis/before_script.sh
  - ./dev/travis/before_script.sh
  - cp $TRAVIS_BUILD_DIR/phpunit.custom.xml.dist dev/tests/unit/phpunit.custom.xml.dist
script:
  - $COMPOSER_BIN_DIR/phpunit -c dev/tests/unit/phpunit.custom.xml.dist
after_script:
  - mysql -e 'DROP DATABASE IF EXISTS magentotravis'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS magentotravis;'
  - php bin/magento setup:install --base-url=https://www.testshop.nl/ --db-host=localhost --db-name=magentotravis --db-user=root --admin-firstname=Dieter --admin-lastname=Demo --admin-email=dieterdemo@payone.com --admin-user=DieterDemo --admin-password=72q980hdfq2378ga9w87dg6 --language=de_DE --currency=EUR --timezone=Europe/Berlin
  - php bin/magento setup:upgrade
  - if php bin/magento setup:di:compile | grep "Errors during compilation"; then exit 1; fi