env:
    #global environmental variables control magento instal parameters
    #see also hosts in addons.
    global:
    - PULSESTORM_MAGE2_FAKE_URL=http://magento-2-travis.dev
    - PULSESTORM_MAGE2_ADMIN_EMAIL=robert.hoffner@example.com
    - PULSESTORM_MAGE2_ADMIN_FIRST_NAME=Robert
    - PULSESTORM_MAGE2_ADMIN_LAST_NAME=Hoffner
    - PULSESTORM_MAGE2_ADMIN_USERNAME=admin
    - PULSESTORM_MAGE2_ADMIN_PASSWORD=ih3artmagento
    - PULSESTORM_MAGE2_ADMIN_DBNAME=magento_2_travis
    - PULSESTORM_COMPOSER_REPOSITORY_TO_TEST=git@github.com:Vendic/RegenerateProductUrls.git
addons:
  hosts:
    # should match PULSESTORM_MAGE2_FAKE_URL above
    - magento-2-travis.dev
language: php
sudo: required
dist: trusty
php:
   - 7.0
before_script:
    - composer selfupdate
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty multiverse" && sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-updates multiverse"
    - sudo apt-get update -qq
    - sudo apt-get remove -y -qq --purge mysql-common mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5 mysql-client-core-5.5
    - sudo apt-get -y -qq autoremove;
    - sudo apt-get -y -qq autoclean;
    - sudo apt-get install -y -qq mysql-server-5.6 mysql-client-5.6;
    - mysql -uroot -e 'SET @@global.sql_mode = NO_ENGINE_SUBSTITUTION; CREATE DATABASE magento_2_travis;';
    - sudo apt-get install -y -qq apache2 libapache2-mod-fastcgi
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf 2>/dev/null || true
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    - sudo chmod 777 /home /home/travis /home/travis/build
    - sudo cp -f .travis/travis-ci-apache /etc/apache2/sites-available/000-default.conf
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
    - sudo service apache2 restart
    - git clone https://github.com/magento/magento2
    # install Magento
    - cd magento2
    # switch to specific branch in you like
    - git checkout 2.0;git checkout tags/2.1.7
    # add composer package under test, composer require will trigger update/install
    - composer config repositories.vendic-regenurl git $PULSESTORM_COMPOSER_REPOSITORY_TO_TEST
    - composer require $PULSESTORM_COMPOSER_PACKAGE_TO_TEST dev-master
    # run installation command using evn variables set above
    - php bin/magento setup:install --admin-email "$PULSESTORM_MAGE2_ADMIN_EMAIL" --admin-firstname "$PULSESTORM_MAGE2_ADMIN_FIRST_NAME" --admin-lastname "$PULSESTORM_MAGE2_ADMIN_LAST_NAME" --admin-password "$PULSESTORM_MAGE2_ADMIN_PASSWORD" --admin-user "$PULSESTORM_MAGE2_ADMIN_USERNAME" --backend-frontname admin --base-url "$PULSESTORM_MAGE2_FAKE_URL" --db-host 127.0.0.1 --db-name magento_2_travis --db-user root --session-save files --use-rewrites 1 --use-secure 0 -vvv
    # test that magento is installed
    - curl "$PULSESTORM_MAGE2_FAKE_URL/index.php" > /tmp/output.txt
script: test 'grep -Fx "magento-2-travis.dev" /tmp/output.txt'