sudo: required
dist: trusty
branches:
  only:
  - gh-pages
  - /.*/
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - postfix
language: php
php:
  - 7.0
env:
  global:
    - MAGENTO_CE_VERSION=2.1.7
    - COMPOSER_BIN_DIR=~/bin
cache:
  apt: true
  directories: $HOME/.composer/cache
before_install:
  # disable xdebug for perf
  - phpenv config-rm xdebug.ini
  # Get latest version of composer
  - composer selfupdate
  # Clone main magento github repository
  - git clone https://github.com/magento/magento2 --branch $MAGENTO_CE_VERSION --depth 1
  - cd magento2
  - composer require vendic/module-regenerateproducturls
before_script: ./dev/travis/before_script.sh
script: vendor/bin/phpunit -c dev/tests/unit/phpunit.xml